### ISSUE TITLE
delete query is returning table names with "_Live" suffix

### ISSUE THREAD

**Issue by bclegaspi** [axllent/silverstripe-version-truncator#15]
in line 195 of src/VersionTruncator.php, the returned queriedTables() includes table name with the suffix  "_Live". I encountered the issue when I upgraded to silverstripe v 4.11, my fix was to fork your code and remove the suffix in the query statement as such:

$srcQuery = DataList::create($this->owner->ClassName)
            ->filter('ID', $this->owner->ID)
            ->dataQuery()
            ->query();
        $queriedTables = $srcQuery->queriedTables();

        foreach ($queriedTables as $table) {
            $delSQL = sprintf(
                'DELETE FROM "%s_Versions"
                    WHERE "Version" IN (%s)
                    AND "RecordID" = %d',
                **str_replace("_Live", "", $table)**,
                implode(',', $to_delete),
                $this->owner->ID
            );
            
          I hope you can consider adding this to your repo :)

**Comment by axllent** [comment]
This is an interesting one as I have never encountered this issue before on any of the websites I have built (they all use this module).  What does the error message say exactly?

**Comment by bclegaspi** [comment]
I didn't encountered this until I upgraded silverstripe from 4.7 to 4.11 although not sure if it's related. The error I am getting when I save a File and then publish it and the error message I am getting is that since the $queriedTables are returning table names with the _Live suffix is "File_Live_Versions table doesn't exists"

**Comment by axllent** [comment]
There must be something else going on here as I'm unable to reproduce this. Is this happening when you update/edit a file within the CMS asset manager, or are you publishing files programmatically via a script or the frontend? Can you confirm that you are using axllent/silverstripe-version-truncator 3.0.0?

**Comment by axllent** [comment]
Actually, I think I can replicate it. Please leave this with me and I'll get back to you soon.

**Comment by axllent** [comment]
No, unfortunately I could not replicate it. @bclegaspi - I am wondering if this is related to #14 which also reported a similar error. I never got feedback the fix I wrote for that so it has not been released yet. Could you please try using the master branch instead `composer require axllent/silverstripe-version-truncator:dev-master` and let me know if that fixes your particular error? If that doesn't work then I can always write a hard-coded exclusion, however I'd prefer not to use messy workarounds if possible.

**Comment by bclegaspi** [comment]
thank you @axllent for looking into this. I also tried using the master branch and unfortunately, still getting the same error. I was thinking it was either the way queriedTables() behaves in silverstripe changed since.

**Comment by axllent** [comment]
@bclegaspi Given that I cannot replicate the error, it is difficult for me to test this or debug why it is happening. I have made another change which hopefully fixes it for you. Sorry, but I'm hesitant to trim `_Live` off the table names as that is just masking the problem - I would rather avoid the problem altogether. Could you please pull in the latest master branch and let me know if this is still giving you an error?

**Comment by axllent** [comment]
This functionality was included recently in 3.0.1. Please feel free to re-open this if you still experience the issue.
