### ISSUE TITLE
Enhancement: Preserve URL history for automatic 301 redirects

### ISSUE THREAD

**Issue by jonom** [axllent/silverstripe-version-truncator#3]
Apologies if this module already does this as I haven't had time to test - but looking at the code I suspect it doesn't.

If you change the URLSegment of a page for example from 'about-us' to 'about', SilverStripe is normally able to automatically redirect users who try to access _site.com/about-us_ to _site.com/about_. It does this by searching through previously published versions of pages for the old URLSegment, and if it finds it it redirects you to the URL of the current published version of the page.

If the old versions aren't there any more, naturally this functionality will be lost.

I propose a new configuration option `preserve_url_history: true` which if enabled (probably should be by default) ensures that at least one version record is left in the table for each unique URLSegment a page had.

**Comment by axllent** [comment]
I have just released a new version of the module (for SilverStripe 4) which has an option to preserve old page versions containing a different URLSegment. I'm not planning to backport it to SS3 though as it has survived this long without, and SS4 should be released in the next couple of months ;-)
