### ISSUE TITLE
Enhancement: Task to run over entire database

### ISSUE THREAD

**Issue by peavers** [axllent/silverstripe-version-truncator#5]
A task to run over the complete database would be a nice feature to have. We have a lot of databases with a large number (over 1000) pages and cleaning those up with a single click would save a lot of time!

**Comment by axllent** [comment]
@peavers I'm just looking for any feedback regarding the development branch I created at the end of last year. I haven't run into any issues testing it here (though I haven't tested heavily), however before merging this into the master branch I thought I'd just ask?

**Comment by peavers** [comment]
I've been running it on local dev and UAT, but not yet inspected the DB to confirm results... Will have a good look on Monday and update. So far though no complaints!

**Comment by torleif** [comment]
I had to modify the script slightly to account for a mysql database that ran with lowercase table names:

**Line 104 VersionTruncator.php**
``` 
			foreach ($versionsToDelete as $d) {
				$subClasses = ClassInfo::dataClassesFor($d['ClassName']);
				foreach ($subClasses as $subClass) {
					if (in_array(strtolower($subClass) . '_versions', $tableList)) {
						DB::query('DELETE FROM "' . strtolower($subClass) . '_versions" WHERE
							"RecordID" = ' . $d['RecordID'] . ' AND "Version" = ' . $d['Version']);
						/* add table to list of accected_tables */
						if (!in_array(strtolower($subClass) . '_versions', $affected_tables)) {
							array_push($affected_tables, strtolower($subClass) . '_versions');
						}
					}
				}
			}
```

Note you wouldn't want to patch the script with this code, just in case someone else ran into the same issue.

**Comment by anselmdk** [comment]
@axllent I just ran `/dev/tasks/VersionTruncatorTask?cleanup=1` on an a huge `SiteTree_versions` table of appr. 150 MB. After running it and optimizing the table via phpmyadmin it's now appr. 30MB.

I'm very happy i found the `development` branch, as that was exactly what I wanted :)

**Comment by axllent** [comment]
@anselmdk That's excellent news! Thank you for testing it, and of course providing me with the valuable feedback. Exactly what I was looking for before replacing the master with the development branch.

Have you by any chance been able to verify that the pages have 10 versions, and that they are the correct versions (ie: last 10 versions)?

**Comment by anselmdk** [comment]
I just checked up on that.
See screenshot.
It's shown like this: `/admin/pages/history/show/952/5`.

Clicking on the revision gives me the following versions (10 of them): 5,7,8,10,11,12,13,14,15, 20.
They seem to be in the right order, I'm wondering why some of them are missing, but can't recall if this is due to something else. This is from a site that I've upgraded from ss24 and that I'm expecting to go live with next week. Before going live I'll take the latest db and go through this one more time. I'll see if I can check how that specific page looked before and after.

![screenshot 2015-05-28 23 33 47](https://cloud.githubusercontent.com/assets/1316533/7871738/136a1d3c-0592-11e5-9671-727fad9c9129.png)

**Comment by axllent** [comment]
The class should delete all except the **latest** 10 (by default) edited versions - so if one was skipping between versions (republishing older versions) - or deleting any versions in between, then this would affect that order, and potentially skip some versions.

The best way to check would be to compare between an old version of the database and the new. I'd appreciate it if you could check that for me some time! Obviously you have a LOT of pages and versions (ie: 150MB worth of history), so take your time, no rush on my behalf :)

**Comment by anselmdk** [comment]
I've noted down that I'll do a test on this before going live, hopefully next week.

**Comment by anselmdk** [comment]
Sorry, I just saw I had this on my list.
I didn't manage to lauch yet, I'll look into it before launching, might take another month though...

**Comment by axllent** [comment]
No problem - I haven't had time to test either. Looking forward to your feedback.

**Comment by anselmdk** [comment]
The site never launched, so it got off my plate, sorry...

**Comment by mspacemedia** [comment]
Come on @anselmdk ;) before I run this on a translatable site with five years of history from ss2.4 :D heh

**Comment by anselmdk** [comment]
@mspacemedia that's one of the kinds of sites we're talking about here. 100s of MB of SiteTree data. Unfortunately the project doesn't seem to go anywhere, that's why it doesn't make much sense for me to spend hours getting back to the project. Sorry.

**Comment by axllent** [comment]
I have just released a new version of the module (for SilverStripe 4) which includes a task to manually run against the entire SiteTree (without you requiring to manually save each page again). It also includes another task to delete ALL unpublished, draft, and older versions of all pages - a "reset" of sorts to keep only the current live versions.

I'm not planning to backport it to SS3 though as it has survived this long without this functionality, and SS4 should be released in the next couple of months.
