### ISSUE TITLE
Adopt semantic versioning releases

### ISSUE THREAD

**Issue by dhensby** [axllent/silverstripe-version-truncator#8]
See [semver](http://semver.org/) and [SilverStripe supported module definition](https://www.silverstripe.org/software/addons/supported-modules-definition/)

Tagging releases is important to allow people to track your project without having to hook onto `dev-master`, which can be unstable and have unexpected consequences.

By adopting semver and an expected version numbering system devs can safely lock onto the correct versions on your software for their projects.

**Comment by axllent** [comment]
Done :-) You are right, and this is something I should adopt for all my modules actually.

I've always been hesitant to release this one though (despite using it in **all* my projects) as it feels like a "quick and dirty" hack (although it is stable). I'm sure there is a more elegant way of doing what it does (your feedback is welcome!). I worked a bit on another branch (see the development branch) which had a few extra features, but (as I just mentioned) still felt like a hack, so I didn't pursue it further.

Maybe you can suggest another way of doing it (ie: using internal `Version` functions), or would this be the way to do it?
